update test

diff --git a/e2e-tests/demand-backup-physical-parallel/run b/e2e-tests/demand-backup-physical-parallel/run
--- a/e2e-tests/demand-backup-physical-parallel/run
+++ b/e2e-tests/demand-backup-physical-parallel/run
@@ -64,6 +64,19 @@ fi
 wait_backup "${backup_name_minio}"
 check_backup_in_storage ${backup_name_minio} minio rs0
 
+reconciliation_count=$(kubectl_bin logs ${OPERATOR_NS:+-n $OPERATOR_NS} $(get_operator_pod) \
+  | grep "main storage changed. starting resync" \
+  | grep "\"name\":\"${cluster}\"" \
+  | wc -l | tr -d ' ')
+
+echo "Reconciliation count: ${reconciliation_count}"
+
+if [ "${reconciliation_count}" -ne 1 ]; then
+    echo "ERROR: Expected 1 reconciliation, got ${reconciliation_count}"
+    echo ""
+    exit 1
+fi
+
 destroy "$namespace"
 
 desc 'test passed'
