fix monitoring test

diff --git a/e2e-tests/monitoring-2-0/run b/e2e-tests/monitoring-2-0/run
--- a/e2e-tests/monitoring-2-0/run
+++ b/e2e-tests/monitoring-2-0/run
@@ -26,6 +26,18 @@ else
 	retry 10 60 helm install monitoring --set imageTag=$IMAGE_PMM_SERVER_TAG --set imageRepo=$IMAGE_PMM_SERVER_REPO --set platform=$platform https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VER}.tgz
 fi
 sleep 20
+SERVICE="postgres"
+until kubectl_bin exec monitoring-0 -- bash -c "pgrep -x $SERVICE >/dev/null"; do
+  echo "Retry $retry"
+  sleep 5
+  let retry+=1
+  if [ $retry -ge 20 ]; then
+    echo "Max retry count $retry reached. Pmm-server can't start"
+    exit 1
+  fi
+done
+ADMIN_PASSWORD=$(kubectl_bin exec monitoring-0 -- bash -c "printenv | grep ADMIN_PASSWORD | cut -d '=' -f2")
+kubectl_bin exec monitoring-0 -- bash -c "grafana-cli --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini admin reset-admin-password $ADMIN_PASSWORD"
 
 desc 'create PSMDB cluster'
 kubectl_bin apply \
@@ -44,7 +56,7 @@ compare_kubectl statefulset/$cluster-rs0
 compare_kubectl service/$cluster-rs0
 compare_kubectl statefulset/$cluster-cfg
 compare_kubectl deployment/$cluster-mongos
-
+sleep 200
 desc 'check mongod metrics'
 get_metric_values node_boot_time_seconds $namespace-$cluster-rs0-1 admin:admin
 get_metric_values mongodb_connections $namespace-$cluster-rs0-1 admin:admin
