K8SPSMDB-1098 fix tls-issue-cert-manager test (#1627)
* K8SPSMDB-1098 fix tls-issue-cert-manager test

* fix liveness test

* fix liveness

* Update e2e-tests/liveness/run

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/e2e-tests/liveness/run b/e2e-tests/liveness/run
--- a/e2e-tests/liveness/run
+++ b/e2e-tests/liveness/run
@@ -18,9 +18,11 @@ spinup_psmdb ${cluster}-rs0 $test_dir/conf/${cluster}-rs0.yml
 desc 'check if statefulset created with expected config'
 compare_kubectl "statefulset/${cluster}-rs0"
 
-# There should be some failed liveness checks during the password change.
-desc 'change MONGODB_CLUSTER_MONITOR_PASSWORD'
-patch_secret "some-users" "MONGODB_CLUSTER_MONITOR_PASSWORD" "$newpassencrypted"
+# There should be some failed liveness checks due to wrong optoins in command
+set +e
+kubectl exec -it $cluster-rs0-0 -- bash -c '/opt/percona/mongodb-healthcheck k8s liveness --ssl'
+set -e
+
 sleep 20
 wait_for_running "${cluster}-rs0" "3"
 
@@ -33,7 +35,7 @@ if [[ $current_log_file != "1" ]]; then
 fi
 
 rotated_log_files=$(kubectl_bin exec -it $cluster-rs0-0 -- bash -c 'ls /data/db/mongod-data/logs' | grep -c "mongodb-healthcheck-.*\.log\.gz")
-if [[ $rotated_log_files != "1" ]]; then
+if [[ $rotated_log_files -lt "1" ]]; then
 	echo "mongodb-healthcheck.log doesn't exist"
 	exit 1
 fi
