Check logic of exact, latest, recommended nad unreached vsersion service responce

diff --git a/e2e-tests/version-service/run b/e2e-tests/version-service/run
--- a/e2e-tests/version-service/run
+++ b/e2e-tests/version-service/run
@@ -6,62 +6,49 @@ set -o xtrace
 test_dir=$(realpath $(dirname $0))
 . ${test_dir}/../functions
 
-desc 'test when version service is reachable'
-cluster="version-service"
+API='psmdb.percona.com/v9-9-9'
+
 create_namespace $namespace
+
+desc 'install version service'
+kubectl_bin create configmap versions --from-file $test_dir/conf/operator.9.9.9.psmdb-operator.dep.json --from-file $test_dir/conf/operator.9.9.9.psmdb-operator.json
+kubectl_bin apply -f $test_dir/conf/vs.yml
+sleep 10
+
 deploy_operator
 
-kubectl_bin apply -f $conf_dir/secrets.yml -f $conf_dir/client.yml
+cases=("version-service-exact" "version-service-recommended" "version-service-latest" "version-service-unreachable")
+expected_images=("percona/percona-server-mongodb:4.2.7-7" "percona/percona-server-mongodb:4.0.20-13" "percona/percona-server-mongodb:4.2.8-8" "$IMAGE_MONGOD")
 
-IMAGE_MONGOD_TO_UPDATE=${IMAGE_MONGOD}
-MONGO_VER=$(echo -n "${IMAGE_MONGOD}" | $sed -r 's/.*([0-9].[0-9])$/\1/')
-IMAGE_MONGOD="percona:psmdb-$MONGO_VER"
+for i in "${!cases[@]}"; do
+	desc "test ${cases[$i]}"
 
-desc 'create PSMDB cluster'
-spinup_psmdb ${cluster}-rs0 $test_dir/conf/${cluster}-rs0.yml
-compare_kubectl "statefulset/${cluster}-rs0"
+	cluster="${cases[$i]}"
+	expected_image="${expected_images[$i]}"
 
-pods=($(kubectl get pods -l app.kubernetes.io/name=percona-server-mongodb -o=name))
-if ${#pods[@]} == 0; then
-	echo "pods not found"
-	exit 1
-fi
+	kubectl_bin apply -f $conf_dir/secrets.yml -f $conf_dir/client.yml
 
-for pod in "${pods[@]}"; do
-	img=$(kubectl get $pod -o jsonpath='{.spec.containers[0].image}')
-	if [ "$img" != "$IMAGE_MONGOD_TO_UPDATE" ]; then
-		echo "image was not updated"
+	desc 'create PSMDB cluster'
+	spinup_psmdb ${cluster}-rs0 $test_dir/conf/${cluster}-rs0.yml
+	compare_kubectl "statefulset/${cluster}-rs0"
+
+	pods=($(kubectl get pods -l app.kubernetes.io/name=percona-server-mongodb -o=name))
+	if ${#pods[@]} == 0; then
+		echo "pods not found"
 		exit 1
 	fi
-done
 
-destroy $namespace
+	for pod in "${pods[@]}"; do
+		img=$(kubectl get $pod -o jsonpath='{.spec.containers[0].image}')
+		if [ "$img" != "$expected_image" ]; then
+			echo "image was not updated"
+			exit 1
+		fi
+	done
 
-namespace="${test_name}-${RANDOM}"
-tmp_dir=$(mktemp -d)
-desc 'test when version service is unreachable'
-cluster="version-service-unreachable"
-create_namespace $namespace
-deploy_operator
-
-kubectl_bin apply -f $conf_dir/secrets.yml -f $conf_dir/client.yml
-
-desc 'create PSMDB cluster'
-spinup_psmdb ${cluster}-rs0 $test_dir/conf/${cluster}-rs0.yml
-compare_kubectl "statefulset/${cluster}-rs0"
-
-pods=($(kubectl get pods -l app.kubernetes.io/name=percona-server-mongodb -o=name))
-if ${#pods[@]} == 0; then
-	echo "pods not found"
-	exit 1
-fi
-
-for pod in "${pods[@]}"; do
-	img=$(kubectl get $pod -o jsonpath='{.spec.containers[0].image}')
-	if [ "$img" != "$IMAGE_MONGOD" ]; then
-		echo "wrong image"
-		exit 1
-	fi
+	kubectl delete pod/$(kubectl get pods | grep operator | awk '{print $1}')
+	kubectl_bin delete psmdb --all
+	sleep 10
 done
 
 destroy $namespace
