Apply suggestions from code review
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/e2e-tests/version-service/run b/e2e-tests/version-service/run
--- a/e2e-tests/version-service/run
+++ b/e2e-tests/version-service/run
@@ -107,56 +107,56 @@ cases=("version-service-exact" "version-service-recommended" "version-service-la
 expected_images=("percona/percona-server-mongodb:4.4.8-9" "percona/percona-server-mongodb:4.4.10-11" "percona/percona-server-mongodb:5.0.10-9" "percona/percona-server-mongodb:4.4.10-11" "$IMAGE_MONGOD")
 
 for i in "${!cases[@]}"; do
-  desc "test ${cases[$i]}"
+	desc "test ${cases[$i]}"
 
-  cluster="${cases[$i]}"
-  expected_image="${expected_images[$i]}"
+	cluster="${cases[$i]}"
+	expected_image="${expected_images[$i]}"
 
-  kubectl_bin apply -f $conf_dir/secrets.yml -f $conf_dir/client.yml
+	kubectl_bin apply -f $conf_dir/secrets.yml -f $conf_dir/client.yml
 
-  desc 'create PSMDB cluster'
-  tmp_file=$(mktemp)
-  sed "s%#initImage%$IMAGE%g" "$test_dir/conf/${cluster}-rs0.yml" >"$tmp_file"
+	desc 'create PSMDB cluster'
+	tmp_file=$(mktemp)
+	sed "s%#initImage%$IMAGE%g" "$test_dir/conf/${cluster}-rs0.yml" >"$tmp_file"
 
-  desc 'create first PSMDB cluster'
-  cat "$tmp_file" |
-    $sed -e "s#apiVersion: psmdb.percona.com/v.*\$#apiVersion: $API#" |
-    $sed -e "s#image:\$#image: $IMAGE_MONGOD#" |
-    $sed -e "s#image:.*-pmm\$#image: $IMAGE_PMM#" |
-    $sed -e "s#image:.*-backup\$#image: $IMAGE_BACKUP#" |
-    $sed -e "s#image: .*-mongod[34].*#image: $IMAGE_MONGOD#" |
-    $sed -e "s#image: .*-mongodb:[34].*#image: $IMAGE_MONGOD#" |
-    yq w - 'spec.backup.enabled' 'false' |
-    yq w - 'spec.backup.tasks' '[]' |
-    kubectl_bin apply -f -
-  desc 'check if Pod is started'
-  wait_for_running "${cluster}-rs0" 3
-  sleep 20
-  compare_kubectl "statefulset/${cluster}-rs0"
-  desc 'write data'
-  run_mongo 'db.createUser({user: "myApp", pwd: "myPass", roles: [{ db: "myApp", role: "readWrite" }]})' \
-    "userAdmin:userAdmin123456@${cluster}-rs0.${namespace}"
+	desc 'create first PSMDB cluster'
+	cat "$tmp_file" \
+		| $sed -e "s#apiVersion: psmdb.percona.com/v.*\$#apiVersion: $API#" \
+		| $sed -e "s#image:\$#image: $IMAGE_MONGOD#" \
+		| $sed -e "s#image:.*-pmm\$#image: $IMAGE_PMM#" \
+		| $sed -e "s#image:.*-backup\$#image: $IMAGE_BACKUP#" \
+		| $sed -e "s#image: .*-mongod[34].*#image: $IMAGE_MONGOD#" \
+		| $sed -e "s#image: .*-mongodb:[34].*#image: $IMAGE_MONGOD#" \
+		| yq w - 'spec.backup.enabled' 'false' \
+		| yq w - 'spec.backup.tasks' '[]' \
+		| kubectl_bin apply -f -
+	desc 'check if Pod is started'
+	wait_for_running "${cluster}-rs0" 3
+	sleep 20
+	compare_kubectl "statefulset/${cluster}-rs0"
+	desc 'write data'
+	run_mongo 'db.createUser({user: "myApp", pwd: "myPass", roles: [{ db: "myApp", role: "readWrite" }]})' \
+		"userAdmin:userAdmin123456@${cluster}-rs0.${namespace}"
 
-  run_mongo 'use myApp\n db.test.insert({ x: 100500 })' "myApp:myPass@${cluster}-rs0.${namespace}"
-  compare_kubectl "statefulset/${cluster}-rs0"
+	run_mongo 'use myApp\n db.test.insert({ x: 100500 })' "myApp:myPass@${cluster}-rs0.${namespace}"
+	compare_kubectl "statefulset/${cluster}-rs0"
 
-  pods=($(kubectl get pods -l app.kubernetes.io/name=percona-server-mongodb -o=name))
-  if [ ${#pods[@]} -eq 0 ]; then
-    echo "pods not found"
-    exit 1
-  fi
+	pods=($(kubectl get pods -l app.kubernetes.io/name=percona-server-mongodb -o=name))
+	if [ ${#pods[@]} -eq 0 ]; then
+		echo "pods not found"
+		exit 1
+	fi
 
-  for pod in "${pods[@]}"; do
-    img=$(kubectl get $pod -o jsonpath='{.spec.containers[0].image}')
-    if [ "$img" != "$expected_image" ]; then
-      echo "image was not updated"
-      exit 1
-    fi
-  done
+	for pod in "${pods[@]}"; do
+		img=$(kubectl get $pod -o jsonpath='{.spec.containers[0].image}')
+		if [ "$img" != "$expected_image" ]; then
+			echo "image was not updated"
+			exit 1
+		fi
+	done
 
-  kubectl delete pod ${OPERATOR_NS:+-n $OPERATOR_NS} $(get_operator_pod)
-  kubectl_bin delete psmdb --all
-  sleep 10
+	kubectl delete pod ${OPERATOR_NS:+-n $OPERATOR_NS} $(get_operator_pod)
+	kubectl_bin delete psmdb --all
+	sleep 10
 done
 
 destroy $namespace
