K8SPSMDB-1553 fixed by preserving restartedAt annotation during StatefulSet recreate (#2182)
* K8SPSMDB-1553 fixed by preserving restartedAt annotation during StatefulSet recreate

* Set restartedAt constant private and add PVC resize test

* improve readability in PVC resize test

---------

Co-authored-by: Ege Güneş <ege.gunes@percona.com>
Co-authored-by: Viacheslav Sarzhan <slava.sarzhan@percona.com>

diff --git a/e2e-tests/pvc-resize/run b/e2e-tests/pvc-resize/run
--- a/e2e-tests/pvc-resize/run
+++ b/e2e-tests/pvc-resize/run
@@ -159,5 +159,38 @@ wait_cluster_status ${cluster} "error"
 patch_pvc_request "${cluster}" "3G"
 wait_cluster_status ${cluster} "ready"
 
+desc "test restartedAt annotation preservation during PVC resize"
+
+echo "delete resourcequota"
+kubectl_bin delete resourcequota default-storage-quota || true
+
+sts_name="${cluster}-rs0"
+kubectl_bin rollout restart statefulset/${sts_name}
+wait_for_running ${sts_name} 3
+
+restarted_at_before=$(kubectl_bin get statefulset ${sts_name} -o jsonpath='{.spec.template.metadata.annotations.kubectl\.kubernetes\.io/restartedAt}')
+[ -z "$restarted_at_before" ] && { echo "ERROR: restartedAt not found"; exit 1; }
+
+patch_pvc_request "${cluster}" "4G"
+wait_all_pvc_resize "4Gi"
+
+sleep_with_log 30 "wait for StatefulSet recreation after orphan delete during PVC resize"
+
+cluster_status=$(kubectl_bin get psmdb "${cluster}" -o jsonpath='{.status.state}')
+restarted_at_after=$(kubectl_bin get statefulset ${sts_name} -o jsonpath='{.spec.template.metadata.annotations.kubectl\.kubernetes\.io/restartedAt}')
+
+if [[ "$restarted_at_before" != "$restarted_at_after" ]]; then
+	echo "ERROR: restartedAt lost"
+	exit 1
+fi
+
+if [[ "$cluster_status" == "initializing" ]]; then
+	echo "ERROR: SmartUpdate occurred (restartedAt not preserved)"
+	exit 1
+fi
+
+wait_cluster_status ${cluster} "ready"
+wait_for_running ${sts_name} 3
+
 destroy "${namespace}"
 desc "test passed"
