ensure that pmm3 test is fully functional

diff --git a/e2e-tests/monitoring-pmm3/run b/e2e-tests/monitoring-pmm3/run
--- a/e2e-tests/monitoring-pmm3/run
+++ b/e2e-tests/monitoring-pmm3/run
@@ -19,7 +19,7 @@ does_node_id_exists() {
 	local -a nodeList=("$@")
 	local -a nodeList_from_pmm=()
 	for node_id in "${nodeList[@]}"; do
-		nodeList_from_pmm+=($(kubectl_bin exec -n "${namespace}" monitoring-0 -- pmm-admin --server-url=https://admin:admin@$(get_pmm_service_ip monitoring-service)/ --server-insecure-tls inventory list nodes --node-type=CONTAINER_NODE | grep $node_id | awk '{print $4}'))
+		nodeList_from_pmm+=($(kubectl_bin exec -n "${namespace}" monitoring-server-0 -- pmm-admin --server-url=https://admin:admin@$(get_pmm_service_ip monitoring-service)/ --server-insecure-tls inventory list nodes --node-type=CONTAINER_NODE | grep $node_id | awk '{print $4}'))
 	done
 
 	echo "${nodeList_from_pmm[@]}"
@@ -38,8 +38,8 @@ check_custom_cluster_name() {
 }
 
 deploy_pmm3_server() {
-  helm repo remove stable || :
-  helm repo add stable https://charts.helm.sh/stable
+	helm repo remove stable || :
+	helm repo add stable https://charts.helm.sh/stable
 	if [[ $OPENSHIFT ]]; then
 		oc create sa pmm-server
 		oc adm policy add-scc-to-user privileged -z pmm-server
@@ -62,12 +62,105 @@ deploy_pmm3_server() {
 	helm repo update
 
 	retry 10 60 helm install monitoring percona/pmm \
-		--set fullnameOverride=monitoring \
-		--set image.tag=3.1.0 \
-		--set image.repository=percona/pmm-server \
+		--set fullnameOverride=monitoring-server \
+		--set image.tag=${IMAGE_PMM3_SERVER#*:} \
+		--set image.repository=${IMAGE_PMM3_SERVER%:*} \
 		--set service.type=LoadBalancer \
 		$additional_params \
 		--force
+}
+
+get_qan_values() {
+	local service_type=$1
+	local environment=$2
+	local token=$3
+	local start
+	local end
+	local endpoint
+	start=$($date -u -d '-12 hour' '+%Y-%m-%dT%H:%M:%S%:z')
+	end=$($date -u '+%Y-%m-%dT%H:%M:%S%:z')
+	endpoint=$(get_service_endpoint monitoring-service)
+
+	cat >payload.json <<EOF
+{
+  "period_start_from": "$start",
+  "period_start_to": "$end",
+  "group_by": "queryid",
+  "labels": [
+    {
+      "key": "service_type",
+      "value": [
+        "$service_type"
+      ]
+    },
+    {
+      "key": "environment",
+      "value": [
+        "$environment"
+      ]
+    }
+  ],
+  "columns": [
+    "load",
+    "num_queries",
+    "query_time"
+  ],
+  "order_by": "-load",
+  "offset": 0,
+  "limit": 10,
+  "main_metric": "load",
+  "search": ""
+}
+EOF
+
+	local response
+
+	local wait_count=30
+	local retry=0
+	until [[ "$(curl -s -k -H "Authorization: Bearer ${token}" -XPOST -d @payload.json "https://$endpoint/v1/qan/metrics:getReport" \
+		| jq '.rows[].fingerprint')" ]]; do
+		sleep 2
+		local start=$($date -u "+%s" -d "-1 minute")
+		local end=$($date -u "+%s")
+		let retry+=1
+		if [[ $retry -ge $wait_count ]]; then
+			exit 1
+		fi
+	done
+	rm -f payload.json
+}
+
+get_metric_values() {
+	local metric=$1
+	local instance=$2
+	local token=$3
+	local start=$($date -u "+%s" -d "-1 minute")
+	local end=$($date -u "+%s")
+	local endpoint=$(get_service_endpoint monitoring-service)
+
+	if [ -z "$metric" ]; then
+		echo "Error: metric is required"
+		exit 1
+	fi
+
+	if [ -z "$token" ]; then
+		echo "Error: token is required"
+		exit 1
+	fi
+
+	local wait_count=30
+	local retry=0
+	until [[ $(curl -s -k -H "Authorization: Bearer ${token}" "https://$endpoint/graph/api/datasources/proxy/1/api/v1/query_range?query=min%28$metric%7Bnode_name%3D%7E%22$instance%22%7d%20or%20$metric%7Bnode_name%3D%7E%22$instance%22%7D%29&start=$start&end=$end&step=60" \
+		| jq '.data.result[0].values[][1]' \
+		| grep '^"[0-9]') ]]; do
+		sleep 2
+		local start=$($date -u "+%s" -d "-1 minute")
+		local end=$($date -u "+%s")
+		let retry+=1
+		if [[ $retry -ge $wait_count ]]; then
+			exit 1
+		fi
+	done
 }
 
 get_pmm_server_token() {
@@ -209,7 +302,7 @@ deploy_cert_manager
 desc 'install PMM Server'
 deploy_pmm3_server
 sleep 20
-until kubectl_bin exec monitoring-0 -- bash -c "ls -l /proc/*/exe 2>/dev/null| grep postgres >/dev/null"; do
+until kubectl_bin exec monitoring-server-0 -- bash -c "ls -l /proc/*/exe 2>/dev/null| grep postgres >/dev/null"; do
 	echo "Retry $retry"
 	sleep 5
 	let retry+=1
@@ -219,7 +312,7 @@ until kubectl_bin exec monitoring-0 -- bash -c "ls -l /proc/*/exe 2>/dev/null| g
 	fi
 done
 
-cluster="monitoring"
+cluster="monitoring-pmm3"
 
 desc 'create secrets and start client'
 kubectl_bin apply \
@@ -231,7 +324,13 @@ yq ".spec.template.spec.volumes[0].secret.secretName=\"$cluster-ssl\"" \
 sleep 90
 
 desc "create first PSMDB cluster $cluster"
-apply_cluster "$test_dir/conf/$cluster-rs0.yml"
+yq eval '(.spec | select(.image == null)).image = "'"$IMAGE_MONGOD"'"' "$test_dir/conf/$cluster-rs0.yml" \
+	| yq eval '(.spec | select(has("pmm"))).pmm.image = "'"$IMAGE_PMM3_CLIENT"'"' - \
+	| yq eval '(.spec | select(has("initImage"))).initImage = "'"$IMAGE"'"' - \
+	| yq eval '(.spec | select(has("backup"))).backup.image = "'"$IMAGE_BACKUP"'"' - \
+	| yq eval '.spec.upgradeOptions.apply = "Never"' - \
+	| kubectl_bin apply -f -
+
 wait_for_running $cluster-rs0 3
 
 desc 'check if pmm-client container is not enabled'
@@ -260,7 +359,6 @@ kubectl_bin patch secret some-users --type merge --patch '{"stringData": {"PMM_S
 
 desc 'check if all 3 Pods started'
 wait_for_running $cluster-rs0 3
-# wait for prometheus
 sleep 90
 
 desc 'check if pmm-client container enabled'
@@ -272,30 +370,29 @@ compare_kubectl statefulset/$cluster-mongos
 
 desc 'create new PMM token and add it to the secret'
 NEW_TOKEN=$(get_pmm_server_token "operator_new")
-kubectl_bin patch some-users --type merge --patch '{"stringData": {"PMM_SERVER_TOKEN": "'"$NEW_TOKEN"'"}}'
+kubectl_bin patch secret some-users --type merge --patch '{"stringData": {"PMM_SERVER_TOKEN": "'"$NEW_TOKEN"'"}}'
 
 desc 'delete old PMM token'
 delete_pmm_server_token "operator"
 
 desc 'check mongod metrics'
-get_metric_values node_boot_time_seconds $namespace-$cluster-rs0-1 admin:admin
-get_metric_values mongodb_connections $namespace-$cluster-rs0-1 admin:admin
+get_metric_values node_boot_time_seconds $namespace-$cluster-rs0-1 $NEW_TOKEN
+get_metric_values mongodb_connections $namespace-$cluster-rs0-1 $NEW_TOKEN
 
-desc 'check mongo config  metrics'
-get_metric_values node_boot_time_seconds $namespace-$cluster-cfg-1 admin:admin
-get_metric_values mongodb_connections $namespace-$cluster-cfg-1 admin:admin
+desc 'check mongo config metrics'
+get_metric_values node_boot_time_seconds $namespace-$cluster-cfg-1 $NEW_TOKEN
+get_metric_values mongodb_connections $namespace-$cluster-cfg-1 $NEW_TOKEN
 
 desc 'check mongos metrics'
 MONGOS_POD_NAME=$(kubectl get pod -l app.kubernetes.io/component=mongos -o jsonpath="{.items[0].metadata.name}")
-get_metric_values node_boot_time_seconds $namespace-$MONGOS_POD_NAME admin:admin
-#get_metric_values mongodb_mongos_connections ${cluster%%-rs0}-mongos-0
+get_metric_values node_boot_time_seconds $namespace-$MONGOS_POD_NAME $NEW_TOKEN
 
-# wait for QAN
+#wait for QAN
 sleep 90
 
 desc 'check QAN data'
-get_qan_values mongodb "dev-mongod" admin:admin
-get_qan_values mongodb "dev-mongos" admin:admin
+get_qan_values mongodb "dev-mongod" $NEW_TOKEN
+get_qan_values mongodb "dev-mongos" $NEW_TOKEN
 
 nodeList=($(get_node_id_from_pmm))
 nodeList_from_pmm=($(does_node_id_exists "${nodeList[@]}"))
@@ -325,17 +422,6 @@ for instance in "${does_node_id_exists_in_pmm[@]}"; do
 	fi
 done
 
-desc 'check customClusterName for pmm'
-custom_name="custom-cluster-name"
-kubectl_bin patch psmdb ${cluster} --type json -p='[{"op":"add","path":"/spec/pause","value":false}, {"op":"add","path":"/spec/pmm/customClusterName","value":'$custom_name'}]'
-wait_for_running $cluster-rs0 3
-
-# get services list from pmm server
-curl -s -k -d '{"service_type":"MONGODB_SERVICE"}' "https://admin:admin@"$(get_service_endpoint monitoring-service)"/v1/inventory/Services/List" >${tmp_dir}/pmm_service_list.json
-check_custom_cluster_name ${namespace}-${cluster}-mongos-0 ${tmp_dir}/pmm_service_list.json
-check_custom_cluster_name ${namespace}-${cluster}-rs0-0 ${tmp_dir}/pmm_service_list.json
-check_custom_cluster_name ${namespace}-${cluster}-cfg-0 ${tmp_dir}/pmm_service_list.json
-
 if [[ -n ${OPENSHIFT} ]]; then
 	oc adm policy remove-scc-from-user privileged -z pmm-server
 	if [ -n "$OPERATOR_NS" ]; then
@@ -345,7 +431,7 @@ if [[ -n ${OPENSHIFT} ]]; then
 	fi
 fi
 
-if [[ $(kubectl_bin logs monitoring-rs0-0 pmm-client | grep -c 'cannot auto discover databases and collections') != 0 ]]; then
+if [[ $(kubectl_bin logs monitoring-pmm3-rs0-0 pmm-client | grep -c 'cannot auto discover databases and collections') != 0 ]]; then
 	echo "error: cannot auto discover databases and collections"
 	exit 1
 fi
