wrapup e2e test

diff --git a/e2e-tests/monitoring-pmm3/run b/e2e-tests/monitoring-pmm3/run
--- a/e2e-tests/monitoring-pmm3/run
+++ b/e2e-tests/monitoring-pmm3/run
@@ -63,8 +63,8 @@ deploy_pmm3_server() {
 
 	retry 10 60 helm install monitoring percona/pmm \
 		--set fullnameOverride=monitoring \
-		--set image.tag=${IMAGE_PMM3_SERVER#*:} \
-		--set image.repository=${IMAGE_PMM3_SERVER%:*} \
+		--set image.tag=3.1.0 \
+		--set image.repository=percona/pmm-server \
 		--set service.type=LoadBalancer \
 		$additional_params \
 		--force
@@ -238,122 +238,122 @@ desc 'check if pmm-client container is not enabled'
 compare_kubectl statefulset/$cluster-rs0 "-no-pmm"
 sleep 10
 
-#custom_port='27019'
-#run_mongos \
-#	'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
-#	"userAdmin:userAdmin123456@$cluster-mongos.$namespace" "" "" \
-#	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
-#run_mongos \
-#	'sh.enableSharding("myApp")' \
-#	"clusterAdmin:clusterAdmin123456@$cluster-mongos.$namespace" "" "" \
-#	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
-#insert_data_mongos "100500" "myApp" \
-#	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
-#insert_data_mongos "100600" "myApp" \
-#	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
-#insert_data_mongos "100700" "myApp" \
-#	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
-#
-#desc 'add PMM3 token to secret'
-#TOKEN=$(get_pmm_server_token "operator")
-#kubectl_bin patch secret some-users --type merge --patch '{"stringData": {"PMM_SERVER_TOKEN": "'"$TOKEN"'"}}'
-#
-#desc 'check if all 3 Pods started'
-#wait_for_running $cluster-rs0 3
-## wait for prometheus
-#sleep 90
-#
-#desc 'check if pmm-client container enabled'
-#compare_kubectl statefulset/$cluster-rs0
-#compare_kubectl service/$cluster-rs0
-#compare_kubectl service/$cluster-mongos
-#compare_kubectl statefulset/$cluster-cfg
-#compare_kubectl statefulset/$cluster-mongos
-#
-#desc 'create new PMM token and add it to the secret'
-#NEW_TOKEN=$(get_pmm_server_token "operator_new")
-#kubectl_bin patch some-users --type merge --patch '{"stringData": {"PMM_SERVER_TOKEN": "'"$NEW_TOKEN"'"}}'
-#
-#desc 'delete old PMM token'
-#delete_pmm_server_token "operator"
+custom_port='27019'
+run_mongos \
+	'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
+	"userAdmin:userAdmin123456@$cluster-mongos.$namespace" "" "" \
+	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
+run_mongos \
+	'sh.enableSharding("myApp")' \
+	"clusterAdmin:clusterAdmin123456@$cluster-mongos.$namespace" "" "" \
+	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
+insert_data_mongos "100500" "myApp" \
+	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
+insert_data_mongos "100600" "myApp" \
+	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
+insert_data_mongos "100700" "myApp" \
+	"--tlsCertificateKeyFile /tmp/tls.pem --tlsCAFile /etc/mongodb-ssl/ca.crt --tls" "$custom_port"
 
-#desc 'check mongod metrics'
-#get_metric_values node_boot_time_seconds $namespace-$cluster-rs0-1 admin:admin
-#get_metric_values mongodb_connections $namespace-$cluster-rs0-1 admin:admin
-#
-#desc 'check mongo config  metrics'
-#get_metric_values node_boot_time_seconds $namespace-$cluster-cfg-1 admin:admin
-#get_metric_values mongodb_connections $namespace-$cluster-cfg-1 admin:admin
-#
-#desc 'check mongos metrics'
-#MONGOS_POD_NAME=$(kubectl get pod -l app.kubernetes.io/component=mongos -o jsonpath="{.items[0].metadata.name}")
-#get_metric_values node_boot_time_seconds $namespace-$MONGOS_POD_NAME admin:admin
-##get_metric_values mongodb_mongos_connections ${cluster%%-rs0}-mongos-0
-#
-## wait for QAN
-#sleep 90
-#
-#desc 'check QAN data'
-#get_qan_values mongodb "dev-mongod" admin:admin
-#get_qan_values mongodb "dev-mongos" admin:admin
-#
-#nodeList=($(get_node_id_from_pmm))
-#nodeList_from_pmm=($(does_node_id_exists "${nodeList[@]}"))
-#for node_id in "${nodeList_from_pmm[@]}"; do
-#	if [ -z "$node_id" ]; then
-#		echo "Can't get $node_id node_id from PMM server"
-#		exit 1
-#	fi
-#done
-#
-#kubectl_bin patch psmdb ${cluster} --type json -p='[{"op":"add","path":"/spec/pause","value":true}]'
-#wait_for_delete "pod/${cluster}-mongos-0"
-#wait_for_delete "pod/${cluster}-rs0-0"
-#wait_for_delete "pod/${cluster}-cfg-0"
-#
-#desc 'check if services are not deleted'
-#
-#kubectl_bin get svc $cluster-rs0
-#kubectl_bin get svc $cluster-cfg
-#kubectl_bin get svc $cluster-mongos
-#
-#does_node_id_exists_in_pmm=($(does_node_id_exists "${nodeList[@]}"))
-#for instance in "${does_node_id_exists_in_pmm[@]}"; do
-#	if [ -n "$instance" ]; then
-#		echo "The $instance pod was not deleted from server inventory"
-#		exit 1
-#	fi
-#done
-#
-#desc 'check customClusterName for pmm'
-#custom_name="custom-cluster-name"
-#kubectl_bin patch psmdb ${cluster} --type json -p='[{"op":"add","path":"/spec/pause","value":false}, {"op":"add","path":"/spec/pmm/customClusterName","value":'$custom_name'}]'
-#wait_for_running $cluster-rs0 3
-#
-## get services list from pmm server
-#curl -s -k -d '{"service_type":"MONGODB_SERVICE"}' "https://admin:admin@"$(get_service_endpoint monitoring-service)"/v1/inventory/Services/List" >${tmp_dir}/pmm_service_list.json
-#check_custom_cluster_name ${namespace}-${cluster}-mongos-0 ${tmp_dir}/pmm_service_list.json
-#check_custom_cluster_name ${namespace}-${cluster}-rs0-0 ${tmp_dir}/pmm_service_list.json
-#check_custom_cluster_name ${namespace}-${cluster}-cfg-0 ${tmp_dir}/pmm_service_list.json
-#
-#if [[ -n ${OPENSHIFT} ]]; then
-#	oc adm policy remove-scc-from-user privileged -z pmm-server
-#	if [ -n "$OPERATOR_NS" ]; then
-#		oc delete clusterrolebinding pmm-psmdb-operator-cluster-wide
-#	else
-#		oc delete rolebinding pmm-psmdb-operator-namespace-only
-#	fi
-#fi
-#
-#if [[ $(kubectl_bin logs monitoring-rs0-0 pmm-client | grep -c 'cannot auto discover databases and collections') != 0 ]]; then
-#	echo "error: cannot auto discover databases and collections"
-#	exit 1
-#fi
-#
-#desc 'check for passwords leak'
-#check_passwords_leak
-#
-#helm uninstall monitoring
-#destroy $namespace
-#
-#desc 'test passed'
+desc 'add PMM3 token to secret'
+TOKEN=$(get_pmm_server_token "operator")
+kubectl_bin patch secret some-users --type merge --patch '{"stringData": {"PMM_SERVER_TOKEN": "'"$TOKEN"'"}}'
+
+desc 'check if all 3 Pods started'
+wait_for_running $cluster-rs0 3
+# wait for prometheus
+sleep 90
+
+desc 'check if pmm-client container enabled'
+compare_kubectl statefulset/$cluster-rs0
+compare_kubectl service/$cluster-rs0
+compare_kubectl service/$cluster-mongos
+compare_kubectl statefulset/$cluster-cfg
+compare_kubectl statefulset/$cluster-mongos
+
+desc 'create new PMM token and add it to the secret'
+NEW_TOKEN=$(get_pmm_server_token "operator_new")
+kubectl_bin patch some-users --type merge --patch '{"stringData": {"PMM_SERVER_TOKEN": "'"$NEW_TOKEN"'"}}'
+
+desc 'delete old PMM token'
+delete_pmm_server_token "operator"
+
+desc 'check mongod metrics'
+get_metric_values node_boot_time_seconds $namespace-$cluster-rs0-1 admin:admin
+get_metric_values mongodb_connections $namespace-$cluster-rs0-1 admin:admin
+
+desc 'check mongo config  metrics'
+get_metric_values node_boot_time_seconds $namespace-$cluster-cfg-1 admin:admin
+get_metric_values mongodb_connections $namespace-$cluster-cfg-1 admin:admin
+
+desc 'check mongos metrics'
+MONGOS_POD_NAME=$(kubectl get pod -l app.kubernetes.io/component=mongos -o jsonpath="{.items[0].metadata.name}")
+get_metric_values node_boot_time_seconds $namespace-$MONGOS_POD_NAME admin:admin
+#get_metric_values mongodb_mongos_connections ${cluster%%-rs0}-mongos-0
+
+# wait for QAN
+sleep 90
+
+desc 'check QAN data'
+get_qan_values mongodb "dev-mongod" admin:admin
+get_qan_values mongodb "dev-mongos" admin:admin
+
+nodeList=($(get_node_id_from_pmm))
+nodeList_from_pmm=($(does_node_id_exists "${nodeList[@]}"))
+for node_id in "${nodeList_from_pmm[@]}"; do
+	if [ -z "$node_id" ]; then
+		echo "Can't get $node_id node_id from PMM server"
+		exit 1
+	fi
+done
+
+kubectl_bin patch psmdb ${cluster} --type json -p='[{"op":"add","path":"/spec/pause","value":true}]'
+wait_for_delete "pod/${cluster}-mongos-0"
+wait_for_delete "pod/${cluster}-rs0-0"
+wait_for_delete "pod/${cluster}-cfg-0"
+
+desc 'check if services are not deleted'
+
+kubectl_bin get svc $cluster-rs0
+kubectl_bin get svc $cluster-cfg
+kubectl_bin get svc $cluster-mongos
+
+does_node_id_exists_in_pmm=($(does_node_id_exists "${nodeList[@]}"))
+for instance in "${does_node_id_exists_in_pmm[@]}"; do
+	if [ -n "$instance" ]; then
+		echo "The $instance pod was not deleted from server inventory"
+		exit 1
+	fi
+done
+
+desc 'check customClusterName for pmm'
+custom_name="custom-cluster-name"
+kubectl_bin patch psmdb ${cluster} --type json -p='[{"op":"add","path":"/spec/pause","value":false}, {"op":"add","path":"/spec/pmm/customClusterName","value":'$custom_name'}]'
+wait_for_running $cluster-rs0 3
+
+# get services list from pmm server
+curl -s -k -d '{"service_type":"MONGODB_SERVICE"}' "https://admin:admin@"$(get_service_endpoint monitoring-service)"/v1/inventory/Services/List" >${tmp_dir}/pmm_service_list.json
+check_custom_cluster_name ${namespace}-${cluster}-mongos-0 ${tmp_dir}/pmm_service_list.json
+check_custom_cluster_name ${namespace}-${cluster}-rs0-0 ${tmp_dir}/pmm_service_list.json
+check_custom_cluster_name ${namespace}-${cluster}-cfg-0 ${tmp_dir}/pmm_service_list.json
+
+if [[ -n ${OPENSHIFT} ]]; then
+	oc adm policy remove-scc-from-user privileged -z pmm-server
+	if [ -n "$OPERATOR_NS" ]; then
+		oc delete clusterrolebinding pmm-psmdb-operator-cluster-wide
+	else
+		oc delete rolebinding pmm-psmdb-operator-namespace-only
+	fi
+fi
+
+if [[ $(kubectl_bin logs monitoring-rs0-0 pmm-client | grep -c 'cannot auto discover databases and collections') != 0 ]]; then
+	echo "error: cannot auto discover databases and collections"
+	exit 1
+fi
+
+desc 'check for passwords leak'
+check_passwords_leak
+
+helm uninstall monitoring
+destroy $namespace
+
+desc 'test passed'
