K8SPSMDB-1413: add `ClusterIssuer` support
https://perconadev.atlassian.net/browse/K8SPSMDB-1413

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -563,56 +563,56 @@ deploy_operator_gh_release() {
 }
 
 deploy_minio() {
-  local cert_secret="$1"
-  local service_name="${2:-minio-service}"
+	local cert_secret="$1"
+	local service_name="${2:-minio-service}"
 
-  desc "install MinIO: ${service_name}"
+	desc "install MinIO: ${service_name}"
 
-  # Cleanup old installation
-  helm uninstall "${service_name}" 2>/dev/null || :
-  helm repo remove minio 2>/dev/null || :
-  helm repo add minio https://charts.min.io/
+	# Cleanup old installation
+	helm uninstall "${service_name}" 2>/dev/null || :
+	helm repo remove minio 2>/dev/null || :
+	helm repo add minio https://charts.min.io/
 
-  local endpoint="http://${service_name}:9000"
-  local minio_args=(
-    --version $MINIO_VER
-    --set replicas=1
-    --set mode=standalone
-    --set resources.requests.memory=256Mi
-    --set rootUser=rootuser
-    --set rootPassword=rootpass123
-    --set "users[0].accessKey=some-access-key"
-    --set "users[0].secretKey=some-secret-key"
-    --set "users[0].policy=consoleAdmin"
-    --set service.type=ClusterIP
-    --set configPathmc=/tmp/
-    --set securityContext.enabled=false
-    --set persistence.size=2G
-    --set fullnameOverride="${service_name}"
-    --set serviceAccount.create=true
-    --set serviceAccount.name="${service_name}-sa"
-  )
+	local endpoint="http://${service_name}:9000"
+	local minio_args=(
+		--version $MINIO_VER
+		--set replicas=1
+		--set mode=standalone
+		--set resources.requests.memory=256Mi
+		--set rootUser=rootuser
+		--set rootPassword=rootpass123
+		--set "users[0].accessKey=some-access-key"
+		--set "users[0].secretKey=some-secret-key"
+		--set "users[0].policy=consoleAdmin"
+		--set service.type=ClusterIP
+		--set configPathmc=/tmp/
+		--set securityContext.enabled=false
+		--set persistence.size=2G
+		--set fullnameOverride="${service_name}"
+		--set serviceAccount.create=true
+		--set serviceAccount.name="${service_name}-sa"
+	)
 
-  if [[ -n $cert_secret ]]; then
-    endpoint="https://${service_name}:9000"
-    minio_args+=(
-      --set tls.enabled=true
-      --set tls.certSecret="$cert_secret"
-    )
-  fi
+	if [[ -n $cert_secret ]]; then
+		endpoint="https://${service_name}:9000"
+		minio_args+=(
+			--set tls.enabled=true
+			--set tls.certSecret="$cert_secret"
+		)
+	fi
 
-  retry 10 60 helm install "${service_name}" "${minio_args[@]}" minio/minio
+	retry 10 60 helm install "${service_name}" "${minio_args[@]}" minio/minio
 
-  local MINIO_POD=$(kubectl_bin get pods --selector=release="${service_name}" -o 'jsonpath={.items[].metadata.name}')
-  wait_pod $MINIO_POD
+	local MINIO_POD=$(kubectl_bin get pods --selector=release="${service_name}" -o 'jsonpath={.items[].metadata.name}')
+	wait_pod $MINIO_POD
 
-  if [ -n "$OPERATOR_NS" ]; then
-    kubectl_bin create svc -n ${OPERATOR_NS} externalname "${service_name}" \
-      --external-name="${service_name}.${namespace}.svc.cluster.local" \
-      --tcp="9000" 2>/dev/null || :
-  fi
+	if [ -n "$OPERATOR_NS" ]; then
+		kubectl_bin create svc -n ${OPERATOR_NS} externalname "${service_name}" \
+			--external-name="${service_name}.${namespace}.svc.cluster.local" \
+			--tcp="9000" 2>/dev/null || :
+	fi
 
-  create_minio_bucket operator-testing $endpoint
+	create_minio_bucket operator-testing $endpoint
 }
 
 create_minio_bucket() {
@@ -1272,6 +1272,8 @@ run_pumba() {
 deploy_cert_manager() {
 	desc 'deploy cert manager'
 
+	kubectl_bin -n cert-manager delete clusterissuer --all || :
+	kubectl_bin -n cert-manager delete certificate --all || :
 	kubectl_bin create namespace cert-manager || :
 	kubectl_bin label namespace cert-manager certmanager.k8s.io/disable-validation=true || :
 	kubectl_bin apply -f "https://github.com/cert-manager/cert-manager/releases/download/v${CERT_MANAGER_VER}/cert-manager.yaml" --validate=false || : 2>/dev/null
