wip

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -34,6 +34,32 @@ conf_dir=$(realpath $test_dir/../conf || :)
 src_dir=$(realpath $test_dir/../..)
 logs_dir=$(realpath $test_dir/../logs || :)
 
+trap 'traperror $? $LINENO $BASH_LINENO "$BASH_COMMAND" $(printf "::%s" ${FUNCNAME[@]:-})' ERR
+trap 'trapexit $? $LINENO' EXIT
+
+function trapexit() {
+  echo "$(date) $(hostname) $0: EXIT on line $2 (exit status $1)"
+}
+
+function traperror () {
+    local err=$1 # error status
+    local line=$2 # LINENO
+    local linecallfunc=$3
+    local command="$4"
+    local funcstack="$5"
+    echo "$(date) $(hostname) $0: ERROR '$command' failed at line $line - exited with status: $err" 
+
+    if [ "$funcstack" != "::" ]; then
+      echo -n "$(date) $(hostname) $0: DEBUG Error in ${funcstack} "
+      if [ "$linecallfunc" != "" ]; then
+        echo "called at line $linecallfunc"
+      else
+        echo
+      fi
+    fi
+    echo "'$command' failed at line $line - exited with status: $err" | mail -s "ERROR: $0 on $(hostname) at $(date)" xxx@xxx.com
+}
+
 if [[ ${ENABLE_LOGGING} == "true" ]]; then
 	if [ ! -d "${logs_dir}" ]; then
 		mkdir "${logs_dir}"
@@ -176,6 +202,11 @@ wait_pod() {
 		sleep 1
 		echo -n .
 		let retry+=1
+		if [[ $(kubectl_bin get pod/${pod} -o jsonpath={.status.containerStatuses[0].state.waiting.reason}) == "ImagePullBackOff" ]]; then
+			echo
+			kubectl_bin get pod/${pod} -o jsonpath={.status.containerStatuses[0].state.waiting.message}
+			exit 1
+		fi
 		if [ $retry -ge 360 ]; then
 			kubectl_bin describe pod/$pod
 			kubectl_bin logs $pod
