K8SPSMDB-234 Yaml beautification

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -18,7 +18,7 @@ test_name=$(basename $test_dir)
 namespace="${test_name}-${RANDOM}"
 conf_dir=$(realpath $test_dir/../conf || :)
 src_dir=$(realpath $test_dir/../..)
-K8SAPI=$(($(kubectl version -o json | jq -r .serverVersion.major) * 100 + $(kubectl version -o json | jq -r .serverVersion.minor | grep -Eo '\d+')))
+
 if oc projects 2>&1 | egrep -q 'You have access to the following projects|You are not a member of any projects|You have one project on this server'; then
     OPENSHIFT=1
 fi
@@ -56,7 +56,7 @@ wait_pod() {
         sleep 1
         echo -n .
         let retry+=1
-        if [ $retry -ge 120 ]; then
+        if [ $retry -ge 360 ]; then
             kubectl_bin describe pod/$pod
             kubectl_bin logs $pod
             kubectl_bin logs $(get_operator_pod) \
@@ -106,7 +106,7 @@ wait_backup_agent() {
         sleep 5
         echo -n .
         let retry+=1
-        if [ $retry -ge 120 ]; then
+        if [ $retry -ge 360 ]; then
             kubectl_bin logs $agent_pod -c backup-agent \
                 | tail -100
             echo max retry count $retry reached. something went wrong with operator or kubernetes cluster
@@ -127,7 +127,7 @@ wait_backup() {
         sleep 1
         echo -n .
         let retry+=1
-        if [ $retry -ge 120 ]; then
+        if [ $retry -ge 360 ]; then
             kubectl_bin logs $(get_operator_pod) \
                 | grep -v 'level=info' \
                 | grep -v 'level=debug' \
@@ -186,7 +186,7 @@ wait_restore_object() {
         sleep 1
         echo -n .
         let retry+=1
-        if [ $retry -ge 120 ]; then
+        if [ $retry -ge 360 ]; then
             kubectl_bin logs $(get_operator_pod) \
                 | grep -v 'level=info' \
                 | grep -v 'level=debug' \
@@ -227,6 +227,7 @@ deploy_minio() {
         --set persistence.size=2G \
         --set environment.MINIO_REGION=us-east-1 \
         --set environment.MINIO_HTTP_TRACE=/tmp/trace.log \
+        --set securityContext.enabled=false \
         stable/minio
     MINIO_POD=$(kubectl_bin get pods --selector=release=minio-service -o 'jsonpath={.items[].metadata.name}')
     wait_pod $MINIO_POD
@@ -256,11 +257,29 @@ retry() {
 wait_for_running() {
     local name="$1"
     let last_pod="$(($2-1))" || :
+    local check_cluster_readyness="${3:-true}"
 
     for i in $(seq 0 $last_pod); do
         wait_pod ${name}-${i}
     done
     sleep 10
+    if [[ ${check_cluster_readyness} == "true" ]]; then
+        set +x
+        echo -n "Waiting for cluster readyness"
+        local timeout=0
+        until [[ $(kubectl_bin get psmdb ${name//-rs0/} -o jsonpath={.status.state}) == "ready" ]]; do
+            sleep 1
+            timeout=$((${timeout}+1))
+            echo -n '.'
+            if [[ ${timeout} -gt 1500 ]]; then
+                echo
+                echo "Waiting timeout has been reached. Exiting..."
+                exit 1
+            fi
+        done
+        echo
+        set -x
+    fi
 }
 
 wait_for_delete() {
@@ -292,30 +311,54 @@ compare_kubectl() {
     local postfix="$2"
     local expected_result=${test_dir}/compare/${resource//\//_}${postfix}.yml
     local new_result="${tmp_dir}/${resource//\//_}.yml"
-    local extra_arg='tee'
 
     if [ "$OPENSHIFT" = 1 -a -f ${expected_result//.yml/-oc.yml} ]; then
         expected_result=${expected_result//.yml/-oc.yml}
     fi
-    if [[ "${K8SAPI}" -ge 118 ]]; then
-        expected_result=${expected_result//.yml/-1.18.yml}
-        extra_arg="yq d - metadata.managedFields"
-    fi
 
     kubectl_bin get -o yaml ${resource} \
-        | ${extra_arg} \
-        | egrep -v "service.kubernetes.io/load-balancer-cleanup" \
-        | egrep -v "namespace:|uid:|resourceVersion:|selfLink:|creationTimestamp:|image:|clusterIP:|dataSource:|procMount:" \
-        | egrep -v "^  storageClassName:|finalizers:|kubernetes.io/pvc-protection|volumeName:|storage-provisioner:|status: \{\}|volumeMode: Filesystem" \
-        | egrep -v "percona.com/.*-hash:|control-plane.alpha.kubernetes.io/leader:|volume.kubernetes.io/selected-node:" \
-        | egrep -v "healthCheckNodePort:|nodePort:" \
-        | $sed -e '/^status:$/,+100500d' \
-        | $sed -e '/NAMESPACE/,+1d' \
-        | $sed -e '/PBM_AGENT_SERVER_ADDRESS/,+1d' \
-        | $sed -e '/name: suffix/,+1d' \
-        | $sed -e '/volumeClaimTemplates:/,/metadata:/d' \
-        | $sed -e '/volumeClaimTemplates:$/{N;/  \- apiVersion.*$/ {N;/  kind.*$/ {N;/    metadata:$/{s/volumeClaimTemplates.*metadata:$/volumeClaimTemplates:\n  \- metadata:/}}}}' \
+        | yq d - 'metadata.managedFields' \
+        | yq d - '**.creationTimestamp' \
+        | yq d - '**.namespace' \
+        | yq d - '**.uid' \
+        | yq d - 'metadata.resourceVersion' \
+        | yq d - 'metadata.selfLink' \
+        | yq d - '**.creationTimestamp' \
+        | yq d - '**.image' \
+        | yq d - '**.clusterIP' \
+        | yq d - '**.dataSource' \
+        | yq d - '**.procMount' \
+        | yq d - '**.storageClassName' \
+        | yq d - '**.finalizers' \
+        | yq d - '**."kubernetes.io/pvc-protection"' \
+        | yq d - '**.volumeName' \
+        | yq d - '**."volume.beta.kubernetes.io/storage-provisioner"' \
+        | yq d - 'spec.volumeMode' \
+        | yq d - '**."volume.kubernetes.io/selected-node"' \
+        | yq d - '**."percona.com/ssl*"' \
+        | yq d - '**.(volumeMode==Filesystem).volumeMode' \
+        | yq d - '**.healthCheckNodePort' \
+        | yq d - '**.nodePort' \
+        | yq d - 'status' \
+        | yq d - '**.(name==NAMESPACE)' \
+        | yq d - '**.(name==PBM_AGENT_SERVER_ADDRESS)' \
+        | yq d - 'spec.volumeClaimTemplates.*.apiVersion' \
+        | yq d - 'spec.volumeClaimTemplates.*.kind' \
         > ${new_result}
+
+
+        # | egrep -v "service.kubernetes.io/load-balancer-cleanup" \
+        # | egrep -v "namespace:|uid:|resourceVersion:|selfLink:|creationTimestamp:|image:|clusterIP:|dataSource:|procMount:" \
+        # | egrep -v "^  storageClassName:|finalizers:|kubernetes.io/pvc-protection|volumeName:|storage-provisioner:|status: \{\}|volumeMode: Filesystem" \
+        # | egrep -v "percona.com/.*-hash:|control-plane.alpha.kubernetes.io/leader:|volume.kubernetes.io/selected-node:" \
+        # | egrep -v "healthCheckNodePort:|nodePort:" \
+        # | $sed -e '/^status:$/,+100500d' \
+        # | $sed -e '/NAMESPACE/,+1d' \
+        # | $sed -e '/PBM_AGENT_SERVER_ADDRESS/,+1d' \
+        # | $sed -e '/name: suffix/,+1d' \
+        # | $sed -e '/volumeClaimTemplates:/,/metadata:/d' \
+        # | $sed -e '/volumeClaimTemplates:$/{N;/  \- apiVersion.*$/ {N;/  kind.*$/ {N;/    metadata:$/{s/volumeClaimTemplates.*metadata:$/volumeClaimTemplates:\n  \- metadata:/}}}}' \
+
     diff -u ${expected_result} ${new_result}
 }
 
