Add demnand-backup sharded to Jekkinsfile

diff --git a/e2e-tests/run b/e2e-tests/run
--- a/e2e-tests/run
+++ b/e2e-tests/run
@@ -3,30 +3,31 @@
 set -o xtrace
 set -o errexit
 
-dir=$(realpath $(dirname $0))
+dir=$(realpath "$(dirname "$0")")
 
 fail() {
-	local test=$1
-	echo "test $test failed"
-	exit 1
+    local test=$1
+    echo "test $test failed"
+    exit 1
 }
 
-$dir/init-deploy/run || fail "init-deploy"
-$dir/limits/run || fail "limits"
-$dir/scaling/run || fail "scaling"
-$dir/monitoring/run || fail "monitoring"
-$dir/monitoring-2-0/run || fail "monitoring-2-0"
-$dir/liveness/run || fail "liveness"
-$dir/one-pod/run || fail "one-pod"
-$dir/service-per-pod/run || fail "service-per-pod"
-$dir/arbiter/run || fail "arbiter"
-$dir/demand-backup/run || fail "demand-backup"
-$dir/scheduled-backup/run || fail "scheduled-backup"
-$dir/upgrade/run || fail "upgrade"
-$dir/upgrade-consistency/run || fail "upgrade-consistency"
-$dir/security-context/run || fail "security-context"
-$dir/storage/run || fail "storage"
-$dir/self-healing/run || fail "self-healing"
-$dir/operator-self-healing/run || fail "operator-self-healing"
-$dir/smart-update || fail "smart-update"
-$dir/version-service || fail "version-service"
+"$dir/init-deploy/run" || fail "init-deploy"
+"$dir/limits/run" || fail "limits"
+"$dir/scaling/run" || fail "scaling"
+"$dir/monitoring/run" || fail "monitoring"
+"$dir/monitoring-2-0/run" || fail "monitoring-2-0"
+"$dir/liveness/run" || fail "liveness"
+"$dir/one-pod/run" || fail "one-pod"
+"$dir/service-per-pod/run" || fail "service-per-pod"
+"$dir/arbiter/run" || fail "arbiter"
+"$dir/demand-backup/run" || fail "demand-backup"
+"$dir/demand-backup-sharded" || fail "demand-backup-sharded"
+"$dir/scheduled-backup/run" || fail "scheduled-backup"
+"$dir/upgrade/run" || fail "upgrade"
+"$dir/upgrade-consistency/run" || fail "upgrade-consistency"
+"$dir/security-context/run" || fail "security-context"
+"$dir/storage/run" || fail "storage"
+"$dir/self-healing/run" || fail "self-healing"
+"$dir/operator-self-healing/run" || fail "operator-self-healing"
+"$dir/smart-update" || fail "smart-update"
+"$dir/version-service" || fail "version-service"
